---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Namespace }}-hub 
  namespace: traefik
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - patch
- apiGroups:
  - traefik.containo.us
  resources:
  - ingressroutetcps
  verbs:
  - get
  - list
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Namespace }}-hub
  namespace: traefik
roleRef:
  kind: Role
  name: {{ .Release.Namespace }}-hub
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: hub
  namespace: {{ .Release.Namespace }}
