---
# Allow singleuser to add DNS entries to traefik service in traefik namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Namespace }}-singleuser
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Namespace }}-singleuser
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Namespace }}-singluser
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: singleuser
  namespace: {{ .Release.Namespace }}


---
# Allow singleuser to modify ingressroutetcps in cmsaf namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Namespace }}-singluser
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - traefik.containo.us
  resources:
  - ingressroutetcps
  verbs:
  - get
  - list
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Namespace }}-singluser
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Namespace }}-singluser
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: singleuser
  namespace: {{ .Release.Namespace }}
